export const propertyData = [
  {
    title: "Palm Harbor",
    price: 2095,
    address: "2699 Green Vally, Highland Lake, FL",
    description: "3 Beds, 2 bathrooms",
    image: "./images/img1.jpeg",
    favourite: "./images/favorite.png",
  },
  {
    title: "Beverly Springfield",
    price: 3095,
    address: "2821 Lake Sevilla, Palm Harbour, TX",
    description: "4 Beds, 3 bathrooms",
    image: "./images/img2.jpeg",
    favourite: "./images/favorite.png",
  },
  {
    title: "Faulkner Ave",
    price: 4770,
    address: "909 Woodland St, Michigan, IN",
    description: "5 Beds, 3 bathrooms",
    image: "./images/img3.jpeg",
    favourite: "./images/favorite.png",
  },
  {
    title: "Adams Wille",
    price: 2700,
    address: "2545 Green Vally, Adams Wille, FL",
    description: "3 Beds, 2 bathrooms",
    image: "./images/img4.jpeg",
    favourite: "./images/favorite.png",
  },
  {
    title: "Williomsons",
    price: 2295,
    address: "4706 O Conner Street, Bethel",
    description: "3 Beds, 2 bathrooms",
    image: "./images/img5.jpeg",
    favourite: "./images/favorite.png",
  },
  {
    title: "Caynor Circle",
    price: 2495,
    address: "4055 Parkway Street,Victorville",
    description: "3 Beds, 2 bathrooms",
    image: "./images/img6.jpeg",
    favourite: "./images/favorite.png",
  },
  {
    title: "Parkway Street",
    price: 3095,
    address: "1181 caynor Circle, Millington",
    description: "3 Beds, 2 bathrooms",
    image: "./images/img7.jpeg",
    favourite: "./images/favorite.png",
  },
  {
    title: "Late Avenue",
    price: 4095,
    address: "3735 Fannie Street,clute",
    description: "4 Beds, 2 bathrooms",
    image: "./images/img8.jpeg",
    favourite: "./images/favorite.png",
  },
  {
    title: "Fannie Street",
    price: 2195,
    address: "202 Late Aveniue Oklahoma city",
    description: "3 Beds, 2 bathrooms",
    image: "./images/img9.jpeg",
    favourite: "./images/favorite.png",
  },
  {
    title: "Terra street",
    price: 2895,
    address: "1390 Rocky Road,Plymouth Meeting",
    description: "3 Beds, 2 bathrooms",
    image: "./images/img10.jpeg",
    favourite: "./images/favorite.png",
  },
  {
    title: "Poplar Street",
    price: 5095,
    address: "2128 Cooks mine Road, Cicero",
    description: "5 Beds, 3 bathrooms",
    image: "./images/img11.jpeg",
    favourite: "./images/favorite.png",
  },
];
